### ISSUE TITLE
Release configuration is broken for amzinet

### ISSUE THREAD

**Issue by fahadash** [AmziLS/interfaces#3]
The dotnet wrapper 'amzinet' is still broken because it is seeking an 'AMZI_DIR' directory in the environment which is not defined. This must be inherited from how the development work was done on this previously. I am simply going to define AMZI_DIR to point at the same lib directory that `AMZI_DEV_DIR` points to since lib contains release package anyway.

**Comment by DennisMerritt** [comment]
AMZI_DIR is supposed to be set to the distribution amzi/apls directory.  It can be part of the normal install.  This might not be the same as AMZI_DEV_DIR.  It’s used, for example, when code is looking for loading various libraries.

—Dennis



On March 16, 2017 at 8:55:51 PM, fahadash (notifications@github.com) wrote:

The dotnet wrapper 'amzinet' is still broken because it is seeking an 'AMZI_DIR' directory in the environment which is not defined. This must be inherited from how the development work was done on this previously. I am simply going to define AMZI_DIR to point at the same lib directory that AMZI_DEV_DIR points to since lib contains release package anyway.
